### ISSUE TITLE
Trailblazer + Tyrant: Session::SignIn returns NoMethodError

### ISSUE THREAD

**Issue by acaron** [apotonick/trailblazer#84]
I don't know if I must post this in Trailblazer or Tyrant, but I followed what the book said about it. I put my `Session` module in `app/concepts/session/operations.rb`but it throws a `NoMethodError`. If I add `Operations` module like so `Session::Operations::SignIn` it, of course, works.

Do you have any idea why? I know `crud.rb`works automatically so it comes from Trailblazer. I must have something missing but the documentation seems to be between two versions (like `callback()` doesn't seems to work with Trailblazer 1.0.0 anymore).

It also throws `NoMethodError: undefined method 'has_key?' for nil:NilClass` when I call the `SignIn` class and it throws `NoMethodError: undefined methodtable_name' for NilClass:Class` when I call the `SignOut`. I really do miss something... the documentation is not very clear about that...

Trailblazer 1.0.0
Trailblazer Rails 0.1.3
Cells 4.0.2
Tyrant 0.0.2

**Comment by acaron** [comment]
Another quick note: it also throws `NoMethodError: undefined method 'has_key?' for nil:NilClass` when I call the `SignIn` class and it throws `NoMethodError: undefined method `table_name' for NilClass:Class` when I call the `SignOut`. I really do miss something... the documentation is not very clear about that...

**Comment by apotonick** [comment]
Hi Annie, can you put the operation into `crud.rb` and report back? I haven't implemented the new autoloading, yet, the book is a bit ahead of the actual framework state as I still play with practices. :beer:

**Comment by acaron** [comment]
It loads, but it requires a `Session` model which don't exist. How do you overwrite that? I tried `setup_model!` and `model!` but I didn't look exactly where the code is autoloading it.

Thanks! :beers:

**Comment by apotonick** [comment]
Here's how I do it presently: https://github.com/apotonick/gemgem-trbrb/blob/chapter-11/app/concepts/session/operations.rb Tyrant is not stable, yet, and it needs a loooot of work for more features (are you keen to help?)?

BTW, join our gitter channel, it's so much easier to discuss things: https://gitter.im/trailblazer/chat

**Comment by acaron** [comment]
Yep this it the way I did it and, like you said, it doesn't work yet! I joined the channel, I will have many questions implementing the new structure :wink: 

Autoloading for operations will be done in Tyrant? I can look at it and help! It is such a great project for Rails.
